package kms

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"sort"
)

// Ciphertext envelope layout:
//
//	[version: 1 byte = 0x01]
//	[key ID: 36 bytes (UUID string)]
//	[algo:   1 byte  (0x01 = SYMMETRIC_DEFAULT)]
//	[nonce:  12 bytes (AES-GCM)]
//	[sealed: variable (plaintext + 16-byte GCM tag)]
const (
	envelopeVersion      = byte(0x01)
	algoSymmetricDefault = byte(0x01)
	envelopeKeyIDOffset  = 1
	envelopeKeyIDLen     = 36
	envelopeAlgoOffset   = 37
	envelopeNonceOffset  = 38
	envelopeNonceLen     = 12
	envelopeSealedOffset = 50
)

// sealEnvelope encrypts plaintext with AES-256-GCM and wraps the result in the
// kumolo ciphertext envelope. nonce must be freshly generated by the caller;
// context is used as AEAD additional data.
func sealEnvelope(
	keyID string,
	material KeyMaterial,
	plaintext []byte,
	context map[string]string,
	nonce [envelopeNonceLen]byte,
) ([]byte, error) {
	block, err := aes.NewCipher(material.KeyBytes)
	if err != nil {
		// untestable: KeyBytes is always 32 bytes (AES-256); wrong-length keys cannot be stored
		return nil, fmt.Errorf("new AES cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		// untestable: standard AES block with NewGCM never fails
		return nil, fmt.Errorf("new GCM: %w", err)
	}

	aad := marshalContext(context)
	sealed := gcm.Seal(nil, nonce[:], plaintext, aad)

	out := make([]byte, envelopeSealedOffset+len(sealed))
	out[0] = envelopeVersion
	copy(out[envelopeKeyIDOffset:], []byte(keyID))
	out[envelopeAlgoOffset] = algoSymmetricDefault
	copy(out[envelopeNonceOffset:], nonce[:])
	copy(out[envelopeSealedOffset:], sealed)
	return out, nil
}

// openEnvelope parses a kumolo ciphertext envelope and decrypts it.
// Returns the embedded keyID, decrypted plaintext, or an error.
func openEnvelope(
	blob []byte,
	material KeyMaterial,
	context map[string]string,
) (embeddedKeyID string, plaintext []byte, err error) {
	if len(blob) < envelopeSealedOffset+1 {
		// unreachable: handleDecrypt validates length before calling openEnvelope
		return "", nil, fmt.Errorf("ciphertext too short")
	}
	if blob[0] != envelopeVersion {
		// unreachable: handleDecrypt validates version byte before calling openEnvelope
		return "", nil, fmt.Errorf("unknown envelope version %d", blob[0])
	}
	embeddedKeyID = string(blob[envelopeKeyIDOffset : envelopeKeyIDOffset+envelopeKeyIDLen])
	algo := blob[envelopeAlgoOffset]
	if algo != algoSymmetricDefault {
		return "", nil, fmt.Errorf("unsupported algorithm code %d", algo)
	}
	nonce := blob[envelopeNonceOffset:envelopeSealedOffset]
	sealed := blob[envelopeSealedOffset:]

	block, err := aes.NewCipher(material.KeyBytes)
	if err != nil {
		// untestable: KeyBytes is always 32 bytes (AES-256); wrong-length keys cannot be stored
		return "", nil, fmt.Errorf("new AES cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		// untestable: standard AES block with NewGCM never fails
		return "", nil, fmt.Errorf("new GCM: %w", err)
	}

	aad := marshalContext(context)
	plaintext, err = gcm.Open(nil, nonce, sealed, aad)
	if err != nil {
		return embeddedKeyID, nil, fmt.Errorf("aead open: %w", err)
	}
	return embeddedKeyID, plaintext, nil
}

// marshalContext produces a deterministic, collision-free byte representation
// of an encryption context for use as AES-GCM additional authenticated data.
// Keys are sorted lexicographically; empty context maps to nil.
// JSON encoding is used so that keys/values containing any byte value
// (including NUL) cannot produce the same serialisation as a different context.
func marshalContext(ctx map[string]string) []byte {
	if len(ctx) == 0 {
		return nil
	}
	keys := make([]string, 0, len(ctx))
	for k := range ctx {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	pairs := make([][2]string, len(keys))
	for i, k := range keys {
		pairs[i] = [2]string{k, ctx[k]}
	}
	b, _ := json.Marshal(pairs)
	return b
}

// validateEncryptionContext returns a non-nil error if any key or value exceeds
// 2048 bytes, or if the total serialised size exceeds 8192 bytes.
func validateEncryptionContext(ctx map[string]string) error {
	for k, v := range ctx {
		if len(k) > 2048 {
			return fmt.Errorf(
				"encryptionContext key length %d exceeds maximum of 2048 bytes", len(k))
		}
		if len(v) > 2048 {
			return fmt.Errorf(
				"encryptionContext value length %d exceeds maximum of 2048 bytes", len(v))
		}
	}
	if serialized := marshalContext(ctx); len(serialized) > 8192 {
		return fmt.Errorf(
			"encryptionContext serialized size %d bytes exceeds maximum of 8192 bytes",
			len(serialized),
		)
	}
	return nil
}

// readFullRand fills dst with random bytes using ro.randRead, treating both an
// error and a short read (n < len(dst)) as failures.
func (ro *Router) readFullRand(dst []byte) error {
	n, err := ro.randRead(dst)
	if err != nil {
		return err
	}
	if n != len(dst) {
		return fmt.Errorf("short random read: got %d bytes, want %d", n, len(dst))
	}
	return nil
}

// looksLikeUUID reports whether s has the 8-4-4-4-12 lowercase-hex UUID shape
// produced by newKeyID. Used to distinguish a malformed ciphertext envelope from
// a legitimately missing key before calling GetKeyMetadata.
func looksLikeUUID(s string) bool {
	if len(s) != 36 {
		return false
	}
	for i, c := range s {
		switch i {
		case 8, 13, 18, 23:
			if c != '-' {
				return false
			}
		default:
			if (c < '0' || c > '9') && (c < 'a' || c > 'f') {
				return false
			}
		}
	}
	return true
}

// resolveAndValidateKey resolves keyID, reads its metadata, and validates that it
// is enabled and has ENCRYPT_DECRYPT usage. Returns the metadata or writes an
// appropriate error response.
func (ro *Router) resolveAndValidateKey(
	w http.ResponseWriter,
	keyIDParam string,
) (KeyMetadata, string, bool) {
	if keyIDParam == "" {
		writeError(w, http.StatusBadRequest, "ValidationException", "KeyId is required")
		return KeyMetadata{}, "", false
	}
	keyID, ok := ro.resolveKeyRef(w, keyIDParam)
	if !ok {
		return KeyMetadata{}, "", false
	}

	meta, err := ro.storage.GetKeyMetadata(keyID)
	if err != nil {
		if errors.Is(err, ErrKeyNotFound) {
			slog.Debug("KMS: key not found", "keyID", keyID)
			writeError(w, http.StatusBadRequest, "NotFoundException",
				fmt.Sprintf("Invalid keyId %s", keyID))
			return KeyMetadata{}, "", false
		}
		slog.Error("KMS: GetKeyMetadata failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return KeyMetadata{}, "", false
	}

	if meta.KeyState == "PendingDeletion" {
		writeError(w, http.StatusBadRequest, "KMSInvalidStateException",
			fmt.Sprintf("KMS key %s is pending deletion", keyID))
		return KeyMetadata{}, "", false
	}
	if !meta.Enabled || meta.KeyState != "Enabled" {
		writeError(w, http.StatusBadRequest, "DisabledException",
			fmt.Sprintf("KMS key %s is disabled", keyID))
		return KeyMetadata{}, "", false
	}
	if meta.KeyUsage != "ENCRYPT_DECRYPT" {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidKeyUsageException",
			fmt.Sprintf(
				"Key %s has KeyUsage %s; ENCRYPT_DECRYPT is required",
				keyID,
				meta.KeyUsage,
			),
		)
		return KeyMetadata{}, "", false
	}

	return meta, keyID, true
}

// loadSymmetricMaterial fetches the key material for a SYMMETRIC_DEFAULT key.
// Writes an error response if the key is not SYMMETRIC_DEFAULT or material is missing.
func (ro *Router) loadSymmetricMaterial(
	w http.ResponseWriter,
	meta KeyMetadata,
	keyID string,
) (KeyMaterial, bool) {
	if meta.KeySpec != "SYMMETRIC_DEFAULT" {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidKeyUsageException",
			fmt.Sprintf(
				"Key %s has KeySpec %s; only SYMMETRIC_DEFAULT keys support this operation in kumolo",
				keyID,
				meta.KeySpec,
			),
		)
		return KeyMaterial{}, false
	}
	mat, err := ro.storage.GetKeyMaterial(keyID)
	if err != nil {
		if errors.Is(err, ErrKeyMaterialNotFound) {
			writeError(w, http.StatusBadRequest, "KMSInvalidStateException",
				fmt.Sprintf("Key material not available for key %s", keyID))
			return KeyMaterial{}, false
		}
		slog.Error("KMS: GetKeyMaterial failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return KeyMaterial{}, false
	}
	return mat, true
}

// ---- Encrypt ---------------------------------------------------------------

func (ro *Router) handleEncrypt(w http.ResponseWriter, body []byte) {
	var req struct {
		KeyID               string            `json:"KeyId"`
		Plaintext           []byte            `json:"Plaintext"`
		EncryptionAlgorithm string            `json:"EncryptionAlgorithm"`
		EncryptionContext   map[string]string `json:"EncryptionContext"`
	}
	if err := json.Unmarshal(body, &req); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", "invalid request body")
		return
	}
	if len(req.Plaintext) == 0 {
		writeError(w, http.StatusBadRequest, "ValidationException", "Plaintext is required")
		return
	}
	if len(req.Plaintext) > 4096 {
		writeError(w, http.StatusBadRequest, "ValidationException",
			fmt.Sprintf("Plaintext length %d exceeds maximum of 4096 bytes", len(req.Plaintext)))
		return
	}
	if req.EncryptionAlgorithm != "" && req.EncryptionAlgorithm != "SYMMETRIC_DEFAULT" {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidKeyUsageException",
			fmt.Sprintf(
				"EncryptionAlgorithm %s is not supported; only SYMMETRIC_DEFAULT is supported in kumolo",
				req.EncryptionAlgorithm,
			),
		)
		return
	}
	if err := validateEncryptionContext(req.EncryptionContext); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", err.Error())
		return
	}

	meta, keyID, ok := ro.resolveAndValidateKey(w, req.KeyID)
	if !ok {
		return
	}
	mat, ok := ro.loadSymmetricMaterial(w, meta, keyID)
	if !ok {
		return
	}

	var nonce [envelopeNonceLen]byte
	if err := ro.readFullRand(nonce[:]); err != nil {
		slog.Error("KMS Encrypt: seal failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return
	}
	ciphertext, err := sealEnvelope(keyID, mat, req.Plaintext, req.EncryptionContext, nonce)
	if err != nil {
		// untestable: sealEnvelope only fails on AES init which cannot fail with 32-byte keys
		slog.Error("KMS Encrypt: seal failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return
	}

	slog.Info("KMS Encrypt", "keyID", keyID)
	writeJSON(w, http.StatusOK, map[string]any{
		"CiphertextBlob":      ciphertext,
		"KeyId":               meta.Arn,
		"EncryptionAlgorithm": "SYMMETRIC_DEFAULT",
	})
}

// ---- Decrypt ---------------------------------------------------------------

func (ro *Router) handleDecrypt(w http.ResponseWriter, body []byte) {
	var req struct {
		CiphertextBlob      []byte            `json:"CiphertextBlob"`
		KeyID               string            `json:"KeyId"`
		EncryptionAlgorithm string            `json:"EncryptionAlgorithm"`
		EncryptionContext   map[string]string `json:"EncryptionContext"`
	}
	if err := json.Unmarshal(body, &req); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", "invalid request body")
		return
	}
	if len(req.CiphertextBlob) == 0 {
		writeError(w, http.StatusBadRequest, "ValidationException", "CiphertextBlob is required")
		return
	}
	if req.EncryptionAlgorithm != "" && req.EncryptionAlgorithm != "SYMMETRIC_DEFAULT" {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidKeyUsageException",
			fmt.Sprintf(
				"EncryptionAlgorithm %s is not supported; only SYMMETRIC_DEFAULT is supported in kumolo",
				req.EncryptionAlgorithm,
			),
		)
		return
	}
	if err := validateEncryptionContext(req.EncryptionContext); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", err.Error())
		return
	}

	// Parse the envelope header to extract the embedded key ID before loading the key.
	if len(req.CiphertextBlob) < envelopeSealedOffset+1 {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidCiphertextException",
			"ciphertext is malformed",
		)
		return
	}
	if req.CiphertextBlob[0] != envelopeVersion {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidCiphertextException",
			"ciphertext is malformed",
		)
		return
	}
	embeddedKeyID := string(
		req.CiphertextBlob[envelopeKeyIDOffset : envelopeKeyIDOffset+envelopeKeyIDLen],
	)
	// Guard against garbage bytes in the key ID slot: without this check,
	// resolveAndValidateKey would return NotFoundException instead of
	// InvalidCiphertextException for malformed ciphertexts.
	if !looksLikeUUID(embeddedKeyID) {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidCiphertextException",
			"ciphertext is malformed",
		)
		return
	}

	// If the caller provided a KeyId, verify it matches the embedded key ID.
	if req.KeyID != "" {
		resolvedID, ok := ro.resolveKeyRef(w, req.KeyID)
		if !ok {
			return
		}
		if resolvedID != embeddedKeyID {
			writeError(
				w,
				http.StatusBadRequest,
				"IncorrectKeyException",
				"The key ID in the request does not match the key used to encrypt the ciphertext",
			)
			return
		}
	}

	meta, keyID, ok := ro.resolveAndValidateKey(w, embeddedKeyID)
	if !ok {
		return
	}
	mat, ok := ro.loadSymmetricMaterial(w, meta, keyID)
	if !ok {
		return
	}

	_, plaintext, err := openEnvelope(req.CiphertextBlob, mat, req.EncryptionContext)
	if err != nil {
		// Try previous key material versions retained after on-demand rotation.
		if prevMats, prevErr := ro.storage.GetPreviousKeyMaterials(keyID); prevErr != nil {
			slog.Warn("kms: GetPreviousKeyMaterials failed", "keyID", keyID, "err", prevErr)
		} else {
			for _, prev := range prevMats {
				if _, pt, tryErr := openEnvelope(req.CiphertextBlob, prev, req.EncryptionContext); tryErr == nil {
					plaintext = pt
					mat = prev
					err = nil
					break
				}
			}
		}
	}
	if err != nil {
		slog.Debug("KMS Decrypt: open envelope failed", "err", err)
		writeError(w, http.StatusBadRequest, "InvalidCiphertextException",
			"ciphertext is invalid or the encryption context does not match")
		return
	}

	slog.Debug("KMS Decrypt", "keyID", keyID)
	writeJSON(w, http.StatusOK, map[string]any{
		"Plaintext":           plaintext,
		"KeyId":               meta.Arn,
		"EncryptionAlgorithm": "SYMMETRIC_DEFAULT",
		"KeyMaterialId":       mat.KeyMaterialID,
	})
}

// ---- GenerateDataKey -------------------------------------------------------

func (ro *Router) handleGenerateDataKey(w http.ResponseWriter, body []byte) {
	keyBytes, ciphertextBlob, arn, materialID, ok := ro.generateDataKeyCommon(w, body)
	if !ok {
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"CiphertextBlob": ciphertextBlob,
		"Plaintext":      keyBytes,
		"KeyId":          arn,
		"KeyMaterialId":  materialID,
	})
}

// ---- GenerateDataKeyWithoutPlaintext ---------------------------------------

func (ro *Router) handleGenerateDataKeyWithoutPlaintext(w http.ResponseWriter, body []byte) {
	_, ciphertextBlob, arn, materialID, ok := ro.generateDataKeyCommon(w, body)
	if !ok {
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"CiphertextBlob": ciphertextBlob,
		"KeyId":          arn,
		"KeyMaterialId":  materialID,
	})
}

// ---- ReEncrypt -------------------------------------------------------------

func (ro *Router) handleReEncrypt(w http.ResponseWriter, body []byte) {
	var req struct {
		CiphertextBlob                 []byte            `json:"CiphertextBlob"`
		DestinationKeyId               string            `json:"DestinationKeyId"`
		SourceKeyId                    string            `json:"SourceKeyId"`
		SourceEncryptionAlgorithm      string            `json:"SourceEncryptionAlgorithm"`
		SourceEncryptionContext        map[string]string `json:"SourceEncryptionContext"`
		DestinationEncryptionAlgorithm string            `json:"DestinationEncryptionAlgorithm"`
		DestinationEncryptionContext   map[string]string `json:"DestinationEncryptionContext"`
	}
	if err := json.Unmarshal(body, &req); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", "invalid request body")
		return
	}
	if len(req.CiphertextBlob) == 0 {
		writeError(w, http.StatusBadRequest, "ValidationException", "CiphertextBlob is required")
		return
	}
	if req.DestinationKeyId == "" {
		writeError(w, http.StatusBadRequest, "ValidationException", "DestinationKeyId is required")
		return
	}
	if req.SourceEncryptionAlgorithm != "" && req.SourceEncryptionAlgorithm != "SYMMETRIC_DEFAULT" {
		writeError(w, http.StatusBadRequest, "InvalidKeyUsageException",
			fmt.Sprintf(
				"SourceEncryptionAlgorithm %s is not supported; only SYMMETRIC_DEFAULT is supported in kumolo",
				req.SourceEncryptionAlgorithm,
			))
		return
	}
	if req.DestinationEncryptionAlgorithm != "" &&
		req.DestinationEncryptionAlgorithm != "SYMMETRIC_DEFAULT" {
		writeError(w, http.StatusBadRequest, "InvalidKeyUsageException",
			fmt.Sprintf(
				"DestinationEncryptionAlgorithm %s is not supported; only SYMMETRIC_DEFAULT is supported in kumolo",
				req.DestinationEncryptionAlgorithm,
			))
		return
	}
	if err := validateEncryptionContext(req.SourceEncryptionContext); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", err.Error())
		return
	}
	if err := validateEncryptionContext(req.DestinationEncryptionContext); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", err.Error())
		return
	}

	// Parse and validate the source ciphertext envelope.
	if len(req.CiphertextBlob) < envelopeSealedOffset+1 {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidCiphertextException",
			"ciphertext is malformed",
		)
		return
	}
	if req.CiphertextBlob[0] != envelopeVersion {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidCiphertextException",
			"ciphertext is malformed",
		)
		return
	}
	embeddedKeyID := string(
		req.CiphertextBlob[envelopeKeyIDOffset : envelopeKeyIDOffset+envelopeKeyIDLen],
	)
	if !looksLikeUUID(embeddedKeyID) {
		writeError(
			w,
			http.StatusBadRequest,
			"InvalidCiphertextException",
			"ciphertext is malformed",
		)
		return
	}

	// If SourceKeyId is provided, verify it matches the embedded key ID.
	if req.SourceKeyId != "" {
		resolvedSrc, ok := ro.resolveKeyRef(w, req.SourceKeyId)
		if !ok {
			return
		}
		if resolvedSrc != embeddedKeyID {
			writeError(w, http.StatusBadRequest, "IncorrectKeyException",
				"The key ID in the request does not match the key used to encrypt the ciphertext")
			return
		}
	}

	// Decrypt with source key.
	srcMeta, srcKeyID, ok := ro.resolveAndValidateKey(w, embeddedKeyID)
	if !ok {
		return
	}
	srcMat, ok := ro.loadSymmetricMaterial(w, srcMeta, srcKeyID)
	if !ok {
		return
	}
	_, plaintext, err := openEnvelope(req.CiphertextBlob, srcMat, req.SourceEncryptionContext)
	if err != nil {
		// Try previous key material versions retained after on-demand rotation.
		if prevMats, prevErr := ro.storage.GetPreviousKeyMaterials(srcKeyID); prevErr != nil {
			slog.Warn("kms: GetPreviousKeyMaterials failed", "keyID", srcKeyID, "err", prevErr)
		} else {
			for _, prev := range prevMats {
				if _, pt, tryErr := openEnvelope(req.CiphertextBlob, prev, req.SourceEncryptionContext); tryErr == nil {
					plaintext = pt
					srcMat = prev
					err = nil
					break
				}
			}
		}
	}
	if err != nil {
		slog.Debug("KMS ReEncrypt: open envelope failed", "err", err)
		writeError(w, http.StatusBadRequest, "InvalidCiphertextException",
			"ciphertext is invalid or the source encryption context does not match")
		return
	}

	// Re-encrypt with destination key.
	dstMeta, dstKeyID, ok := ro.resolveAndValidateKey(w, req.DestinationKeyId)
	if !ok {
		return
	}
	dstMat, ok := ro.loadSymmetricMaterial(w, dstMeta, dstKeyID)
	if !ok {
		return
	}

	var nonce [envelopeNonceLen]byte
	if err := ro.readFullRand(nonce[:]); err != nil {
		slog.Error("KMS ReEncrypt: rand read failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return
	}
	newCiphertext, err := sealEnvelope(
		dstKeyID,
		dstMat,
		plaintext,
		req.DestinationEncryptionContext,
		nonce,
	)
	if err != nil {
		// untestable: sealEnvelope only fails on AES init which cannot fail with 32-byte keys
		slog.Error("KMS ReEncrypt: seal failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return
	}

	slog.Info("KMS ReEncrypt", "sourceKeyID", srcKeyID, "destKeyID", dstKeyID)
	writeJSON(w, http.StatusOK, map[string]any{
		"CiphertextBlob":                 newCiphertext,
		"KeyId":                          dstMeta.Arn,
		"SourceKeyId":                    srcMeta.Arn,
		"SourceEncryptionAlgorithm":      "SYMMETRIC_DEFAULT",
		"SourceKeyMaterialId":            srcMat.KeyMaterialID,
		"DestinationEncryptionAlgorithm": "SYMMETRIC_DEFAULT",
		"DestinationKeyMaterialId":       dstMat.KeyMaterialID,
	})
}

// ---- GenerateRandom --------------------------------------------------------

func (ro *Router) handleGenerateRandom(w http.ResponseWriter, body []byte) {
	var req struct {
		NumberOfBytes    *int   `json:"NumberOfBytes"`
		CustomKeyStoreId string `json:"CustomKeyStoreId"`
	}
	if err := json.Unmarshal(body, &req); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", "invalid request body")
		return
	}
	if req.CustomKeyStoreId != "" {
		writeError(w, http.StatusBadRequest, "UnsupportedOperationException",
			"CustomKeyStoreId is not supported")
		return
	}
	if req.NumberOfBytes == nil {
		writeError(w, http.StatusBadRequest, "ValidationException", "NumberOfBytes is required")
		return
	}
	n := *req.NumberOfBytes
	if n < 1 || n > 1024 {
		writeError(w, http.StatusBadRequest, "ValidationException",
			fmt.Sprintf("NumberOfBytes must be between 1 and 1024, got %d", n))
		return
	}

	buf := make([]byte, n)
	if err := ro.readFullRand(buf); err != nil {
		slog.Error("KMS GenerateRandom: rand read failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return
	}

	slog.Debug("KMS GenerateRandom", "numberOfBytes", n)
	writeJSON(w, http.StatusOK, map[string]any{
		"Plaintext": buf,
	})
}

// validKeyPairSpecs is the set of KeyPairSpec values accepted by GenerateDataKeyPair(WithoutPlaintext).
var validKeyPairSpecs = map[string]bool{
	"RSA_2048":              true,
	"RSA_3072":              true,
	"RSA_4096":              true,
	"ECC_NIST_P256":         true,
	"ECC_NIST_P384":         true,
	"ECC_NIST_P521":         true,
	"ECC_SECG_P256K1":       true,
	"SM2":                   true,
	"ECC_NIST_EDWARDS25519": true,
}

// ---- GenerateDataKeyPair ---------------------------------------------------

func (ro *Router) handleGenerateDataKeyPair(w http.ResponseWriter, body []byte) {
	privKeyDER, pubKeyDER, ciphertextBlob, spec, arn, materialID, ok :=
		ro.generateDataKeyPairCommon(w, body)
	if !ok {
		return
	}
	slog.Info("KMS GenerateDataKeyPair", "keyPairSpec", spec)
	writeJSON(w, http.StatusOK, map[string]any{
		"KeyId":                    arn,
		"KeyPairSpec":              spec,
		"PublicKey":                pubKeyDER,
		"PrivateKeyPlaintext":      privKeyDER,
		"PrivateKeyCiphertextBlob": ciphertextBlob,
		"KeyMaterialId":            materialID,
	})
}

// ---- GenerateDataKeyPairWithoutPlaintext -----------------------------------

func (ro *Router) handleGenerateDataKeyPairWithoutPlaintext(w http.ResponseWriter, body []byte) {
	_, pubKeyDER, ciphertextBlob, spec, arn, materialID, ok :=
		ro.generateDataKeyPairCommon(w, body)
	if !ok {
		return
	}
	slog.Info("KMS GenerateDataKeyPairWithoutPlaintext", "keyPairSpec", spec)
	writeJSON(w, http.StatusOK, map[string]any{
		"KeyId":                    arn,
		"KeyPairSpec":              spec,
		"PublicKey":                pubKeyDER,
		"PrivateKeyCiphertextBlob": ciphertextBlob,
		"KeyMaterialId":            materialID,
	})
}

// generateDataKeyPairCommon handles the shared logic of GenerateDataKeyPair and
// GenerateDataKeyPairWithoutPlaintext. Returns (privKeyDER, pubKeyDER, ciphertextBlob, spec, arn, materialID, ok).
func (ro *Router) generateDataKeyPairCommon(
	w http.ResponseWriter,
	body []byte,
) ([]byte, []byte, []byte, string, string, string, bool) {
	var req struct {
		KeyID             string            `json:"KeyId"`
		KeyPairSpec       string            `json:"KeyPairSpec"`
		EncryptionContext map[string]string `json:"EncryptionContext"`
	}
	if err := json.Unmarshal(body, &req); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", "invalid request body")
		return nil, nil, nil, "", "", "", false
	}
	if req.KeyID == "" {
		writeError(w, http.StatusBadRequest, "ValidationException", "KeyId is required")
		return nil, nil, nil, "", "", "", false
	}
	if req.KeyPairSpec == "" {
		writeError(w, http.StatusBadRequest, "ValidationException", "KeyPairSpec is required")
		return nil, nil, nil, "", "", "", false
	}
	if !validKeyPairSpecs[req.KeyPairSpec] {
		writeError(w, http.StatusBadRequest, "ValidationException",
			fmt.Sprintf("Invalid KeyPairSpec: %s", req.KeyPairSpec))
		return nil, nil, nil, "", "", "", false
	}
	if err := validateEncryptionContext(req.EncryptionContext); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", err.Error())
		return nil, nil, nil, "", "", "", false
	}

	meta, keyID, ok := ro.resolveAndValidateKey(w, req.KeyID)
	if !ok {
		return nil, nil, nil, "", "", "", false
	}
	mat, ok := ro.loadSymmetricMaterial(w, meta, keyID)
	if !ok {
		return nil, nil, nil, "", "", "", false
	}

	privKeyDER, err := ro.generateEphemeralKeyPairFn(req.KeyPairSpec)
	if err != nil {
		slog.Error("KMS GenerateDataKeyPair: key generation failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return nil, nil, nil, "", "", "", false
	}
	if privKeyDER == nil {
		writeError(w, http.StatusBadRequest, "UnsupportedOperationException",
			fmt.Sprintf("KeyPairSpec %s is not supported in kumolo", req.KeyPairSpec))
		return nil, nil, nil, "", "", "", false
	}

	pubKeyDER, err := extractPublicKeyDER(privKeyDER)
	if err != nil {
		slog.Error("KMS GenerateDataKeyPair: extract public key failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return nil, nil, nil, "", "", "", false
	}

	var nonce [envelopeNonceLen]byte
	if err := ro.readFullRand(nonce[:]); err != nil {
		slog.Error("KMS GenerateDataKeyPair: rand read failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return nil, nil, nil, "", "", "", false
	}
	ciphertextBlob, err := sealEnvelope(keyID, mat, privKeyDER, req.EncryptionContext, nonce)
	if err != nil {
		// untestable: sealEnvelope only fails on AES init which cannot fail with 32-byte keys
		slog.Error("KMS GenerateDataKeyPair: seal failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return nil, nil, nil, "", "", "", false
	}

	return privKeyDER, pubKeyDER, ciphertextBlob, req.KeyPairSpec, meta.Arn, mat.KeyMaterialID, true
}

// generateDataKeyCommon handles the shared logic of GenerateDataKey and
// GenerateDataKeyWithoutPlaintext. Returns (rawKeyBytes, ciphertext, arn, materialID, ok).
func (ro *Router) generateDataKeyCommon(
	w http.ResponseWriter,
	body []byte,
) ([]byte, []byte, string, string, bool) {
	var req struct {
		KeyID             string            `json:"KeyId"`
		KeySpec           string            `json:"KeySpec"`
		NumberOfBytes     *int              `json:"NumberOfBytes"`
		EncryptionContext map[string]string `json:"EncryptionContext"`
	}
	if err := json.Unmarshal(body, &req); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", "invalid request body")
		return nil, nil, "", "", false
	}

	// Exactly one of KeySpec or NumberOfBytes must be set.
	if req.KeySpec != "" && req.NumberOfBytes != nil {
		writeError(w, http.StatusBadRequest, "ValidationException",
			"specify either KeySpec or NumberOfBytes, not both")
		return nil, nil, "", "", false
	}
	if req.KeySpec == "" && req.NumberOfBytes == nil {
		writeError(w, http.StatusBadRequest, "ValidationException",
			"specify either KeySpec or NumberOfBytes")
		return nil, nil, "", "", false
	}

	var numBytes int
	switch req.KeySpec {
	case "AES_256":
		numBytes = 32
	case "AES_128":
		numBytes = 16
	case "":
		numBytes = *req.NumberOfBytes
		if numBytes < 1 || numBytes > 1024 {
			writeError(w, http.StatusBadRequest, "ValidationException",
				fmt.Sprintf("NumberOfBytes must be between 1 and 1024, got %d", numBytes))
			return nil, nil, "", "", false
		}
	default:
		writeError(w, http.StatusBadRequest, "ValidationException",
			fmt.Sprintf("Invalid KeySpec: %s; valid values are AES_256 and AES_128", req.KeySpec))
		return nil, nil, "", "", false
	}

	if err := validateEncryptionContext(req.EncryptionContext); err != nil {
		writeError(w, http.StatusBadRequest, "ValidationException", err.Error())
		return nil, nil, "", "", false
	}

	meta, keyID, ok := ro.resolveAndValidateKey(w, req.KeyID)
	if !ok {
		return nil, nil, "", "", false
	}
	mat, ok := ro.loadSymmetricMaterial(w, meta, keyID)
	if !ok {
		return nil, nil, "", "", false
	}

	// Generate data key bytes and envelope nonce in a single randRead call so
	// both derive from the same PRNG invocation, avoiding two-call ordering risks.
	combined := make([]byte, numBytes+envelopeNonceLen)
	if err := ro.readFullRand(combined); err != nil {
		slog.Error("KMS GenerateDataKey: rand read failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return nil, nil, "", "", false
	}
	dataKey := combined[:numBytes]
	var nonce [envelopeNonceLen]byte
	copy(nonce[:], combined[numBytes:])

	ciphertextBlob, err := sealEnvelope(keyID, mat, dataKey, req.EncryptionContext, nonce)
	if err != nil {
		// untestable: sealEnvelope only fails on AES init which cannot fail with 32-byte keys
		slog.Error("KMS GenerateDataKey: seal failure", "err", err)
		writeError(
			w,
			http.StatusInternalServerError,
			"KMSInternalException",
			"internal server error",
		)
		return nil, nil, "", "", false
	}

	slog.Info("KMS GenerateDataKey", "keyID", keyID, "numBytes", numBytes)
	return dataKey, ciphertextBlob, meta.Arn, mat.KeyMaterialID, true
}
